language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "HSYo+l3EGkOote4atfs7NxAmvNTWtr840G43PbjW/WtbfKf5qYN7CyS26ROAN1HgyAN2njSfVY0Wlbk3BCR6MV+vexZU35FvnKqFk0LrkvNWRpiL0LZgfRP7YO8mjNn8jVhg2EscWm32tgK85fHtY3bCOY4Ve+nTDNImsjP1Mbay1YOAoJzMB+P0s4mThTESKVE/raxJ2qeSI88RyAFFKsHGwdihXE7vSJqZdntxC8HUs2xRVnwSVgNQLQQEwVYv0wWYsi3bz9+kO54c2mlNFrS4SjTBXhPpysKCYOtoIA2sac46+yp87YqA+H0edWl2xqcS0NOLiUYeWkG6HiUSyj60u3WqYhCroUGRJsM2Ue4/Oeyb8fnFMKyIiiRuOS3Ki/fAI+kGckpKsE9waUhp9GfOM0Hbz/XdSHkukUFx3OTOYyfefPn8azFkXhXiXnpKHoGpKB/Q1BvHHCtKGLa01JZgA0Y5b3w1Rmhm/JXpaiU/v/tw8TvkKv3hT/22s4fHDfJxUBAsLvj3QVZMsiPbq4063EjVPMYlKl7Ha2Pvn+/UDeoWsbyVP0TsL+XT+DvUb31kqju9HcF5TUgRYh98IxUWSE3mxEYHRn9YzRvuG1lkTF03yvWHRqDdCldQyyKdKXw4ioIl5QrB2RI3ccdgvqLBPfziQrDYUqwSWdxSKIo="
